### PR TITLE
2.0.6 proposal: Fixed HA Deprecation, Error Handling, Resources Management

### PR DESCRIPTION
**Pull request by ms1design**
Hi @mudape 👋 

Added few fixes to ensure proper resource cleanup and prevent resource leaks, ensuring the stability and reliability of the code:
- Replaced `SOURCE_TYPE_ROUTER` with `SourceType.ROUTER` (#101).
- Wrapped the code that might raise exceptions in try-except blocks.
- Use the `closing` context manager from the `contextlib` module to ensure that the `IPRoute` instance is properly closed after use, even if an exception occurs within the block. The `closing` context manager ensures that the `__exit__` method of the `IPRoute` instance is always called, allowing it to release any associated resources. 

  The `IPRoute` class from the `pyroute2` library interacts with system resources, and not closing instances of it could lead to resource leaks. Each instance of `IPRoute` may allocate file descriptors for communication with the kernel's `netlink` subsystem, and if these descriptors are not released, they can accumulate over time, leading to the observed behavior in #99 .
- If an exception occurs while querying the network state using `IPRoute`, it's caught and handled gracefully, and a default state value is used instead.

### CODE REVIEW

**Comment by mudape** [comment]
@ms1design Sorry, I messed stuff up when trying to be quick during the lunchbreak

**Comment by ms1design** [comment]
@mudape did you had time to take a look on this one? What's you take on?

**Comment by mudape** [comment]
@ms1design 
Yes, looks fine :)
I only have access to my office PC which lacks git and also haven't been keeping up to with this for months..
This lead to me totally breaking your PR
The code you submitted to the branch with me copy/pasting :/

**Comment by ms1design** [comment]
No worries chap :) Please ping me in a comment when you will be sorted out with your changes and I can update this PR before merging. @mudape it's better to review PR's first instead of copy-paste ;)

**Pull request closed without merging**
