### PR TITLE
Add mac, host_name and gps arguments to device_tracker.see method

### PR DESCRIPTION
**Pull request by bieniu**
This PR adds `mac`, `host_name` and `gps` arguments to `device_tracker.see` method. GPS coordinates are from Home Assistant home zone.

Fix https://github.com/mudape/iphonedetect/issues/28

### CODE REVIEW

**Comment by mudape** [comment]
Hi @bieniu,

Thanks for the PR!
I haven't used Map or tracked devices outside of home so didn't think of this.

Thoughts:
Adding mac creates a new device entry in known_devices.yaml.
However, the features seems to works fine without mac address.
So, to avoid having ppl update known_devices.yaml or relations to their entities how about skipping that for now?

Also, I don't know what value 'host_name' adds?

**Comment by bieniu** [comment]
In my configuration `mac` value has been added to an existing entry.
`host_name` is corresponds to `name` field in entry in known_devices.yaml.
I think the `mac` argument is very important because it allows to combine data from several device_tracker components in one entry.

**Comment by bieniu** [comment]
@mudape Don't you want merge this PR?

**Comment by mudape** [comment]
Hi @bieniu,

At this point no, I don't wont to merge this pr.

The reason is that adding mac to an existing device (which don't already have that) in know_devices.yaml creates a new entity.
That 'breaks' the current configuration but doesn't really add function to this integration.

I also fail to see what gps location adds to this integration.
- It's a router tracker
- Device in zone home don't show on the map
- Other trackers can be added to the Person for same function

For host_name that's just the friendly name which typically you set in Lovelace anyhow.

So while the PR do work and adds stuff, I don't see this adding features to the integration that motivates that users potentially need to adjust their configuration.

With that said maybe other also see a need for this, so I'll leave it open.
I would like to move away from know_devices.yaml though...

**Comment by bieniu** [comment]
> I would like to move away from know_devices.yaml though...

This is the best direction.

**Pull request closed without merging**
